"""empty message

Revision ID: c8d9ccdaeff6
Revises: ed1c8e5f873e
Create Date: 2023-07-15 13:20:24.438662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d9ccdaeff6'
down_revision = 'ed1c8e5f873e'
branch_labels = None
depends_on = None

naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.add_column(sa.Column('_owner_id', sa.String(), nullable=False))
        batch_op.drop_constraint('fk_client_owner_id_user', type_='foreignkey')
        batch_op.create_foreign_key('fk_client_owner_id_user', 'user', ['_owner_id'], ['fs_uniquifier'])
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['owner_id'], ['fs_uniquifier'])
        batch_op.drop_column('_owner_id')

    # ### end Alembic commands ###
